### ISSUE TITLE
aws-sdk clients missing from dependencies

### ISSUE THREAD

**Issue by rjmackay** [fedonev/lambda-params-secrets#9]
### What happened?

I'm getting errors when trying to build a package using this module.

Error: node_modules/lambda-params-secrets/lib/responses.d.ts(1,32): error TS2307: Cannot find module '@aws-sdk/client-ssm' or its corresponding type declarations.
Error: node_modules/lambda-params-secrets/lib/responses.d.ts(2,50): error TS2307: Cannot find module '@aws-sdk/client-secrets-manager' or its corresponding type declarations.

Looking at the code I'm not entirely clear if these are required during runtime, or just in the typedefs. But building with tsc breaks because it's missing those modules.

### Possible Solution

Add @aws-sdk/client-ssm and @aws-sdk/client-secrets-manager to `dependencies` in package.json

### Package Version

0.1.0

### Lambda Node.js Version

16

**Comment by rjmackay** [comment]
I think those are declared in dev deps already, but should probably be either peerDependencies or dependencies?

**Comment by fedonev** [comment]
Thanks for reporting the problem.  Let me take a look.

**Comment by rjmackay** [comment]
@fedonev I think this needs to be a peer dependency. Adding them direct to dependencies seems to have drastically increased the bundle size of this package.
